### ISSUE TITLE
Errors on key up

### ISSUE THREAD

**Issue by mkahvi** [WesBelmont/token-lean#12]
```
script.mjs:57 Uncaught TypeError: Cannot read properties of undefined (reading 'center')
[Detected 1 package: token-lean]
    at enableLean (script.mjs:57:43)
    at Object.onUp (script.mjs:41:13)
    at Function._executeKeybind (foundry.js:1629:58)
    at KeyboardManager._processKeyboardContext (foundry.js:1669:33)
    at KeyboardManager._handleKeyboardEvent (foundry.js:1707:10)
    at foundry.js:1362:54
```

This happens with and without token being selected.

**Comment by WesBelmont** [comment]
This doesn't seem to be a problem anymore. Thanks for the report anyway.
