### ISSUE TITLE
[BUG] The module is breaking character selection with the new version (357) of Levels.

### ISSUE THREAD

**Issue by rinnocenti** [WesBelmont/token-lean#20]
with the module turned on, it is not possible to properly select tokens

![Captura de tela 2022-11-30 130636](https://user-images.githubusercontent.com/3178127/204849361-1bb43a04-316d-46dd-a639-ed873dbbed34.png)

**Comment by InstantZzz** [comment]
I am having the same or a similar issue. Main difference I am seeing is that my error also references my game system under detected packages; my system being Pathfinder 2E.

"libWrapper-wrapper.js:669 Uncaught TypeError: Cannot read properties of undefined (reading 'elevation')
[Detected 5 packages: token-lean, lib-wrapper, levels, perfect-vision, system:pf2e]
    at 🎁CONFIG.Levels.handlers.SightHandler.advancedLosTestInLos#token-lean (levels.mjs:39:20)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:591:14)
    at 🎁CONFIG.Levels.handlers.SightHandler.advancedLosTestInLos#0 (libWrapper-wrapper.js:189:20)
    at SightHandler.advancedLosTestVisibility (sightHandler.js:20:18)
    at SightHandler.performLOSTest (sightHandler.js:14:17)
    at ClockwiseSweepPolygon.containsWrapper (sightHandler.js:214:53)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁ClockwiseSweepPolygon.prototype.contains#0 (libWrapper-wrapper.js:189:20)
    at 🎁DetectionMode.prototype._testLOS#perfect-vision (detection-mode.js:93:34)
    at 🎁DetectionMode.prototype._testLOS#0 (libWrapper-wrapper.js:187:52)
    at 🎁DetectionModeBasicSight.prototype._testPoint#perfect-vision (detection-mode.js:146:23)
    at 🎁DetectionModeBasicSight.prototype._testPoint#0 (libWrapper-wrapper.js:187:52)
    at foundry.js:40582:36
    at Array.some (<anonymous>)
    at VisionDetectionMode.testVisibility (foundry.js:40582:18)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁DetectionMode.prototype.testVisibility#levels (wrappers.js:160:20)
    at 🎁DetectionMode.prototype.testVisibility#0 (libWrapper-wrapper.js:187:52)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁DetectionModeBasicSight.prototype.testVisibility#perfect-vision (detection-mode.js:126:28)
    at 🎁DetectionModeBasicSight.prototype.testVisibility#0 (libWrapper-wrapper.js:187:52)
    at VisionDetectionMode.testVisibility (main.bundle.js:1:533061)
    at CanvasVisibility.testVisibility (foundry.js:33378:39)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at CanvasVisibility.visibilityWrapper (wrappers.js:122:25)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁CanvasVisibility.prototype.testVisibility#0 (libWrapper-wrapper.js:189:20)
    at get isVisible (foundry.js:45430:38)
    at get isVisible [as isVisible] (main.bundle.js:1:556118)
    at CanvasVisibility.restrictVisibility (foundry.js:33300:68)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁CanvasVisibility.prototype.restrictVisibility#perfect-vision (visibility.js:46:20)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁CanvasVisibility.prototype.restrictVisibility#0 (libWrapper-wrapper.js:189:20)
    at 🎁CanvasVisibility.prototype.refresh#perfect-vision (visibility.js:391:18)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:591:14)
    at 🎁CanvasVisibility.prototype.refresh#0 (libWrapper-wrapper.js:189:20)
    at #update (foundry.js:41344:58)
    at t.emit (ticker.min.mjs:8:622)
    at e.update (ticker.min.mjs:8:3473)
    at _tick (ticker.min.mjs:8:1482)"

**Comment by ilore** [comment]
Same here. With levels, every time you select a token, the scene freezes, and you need to reload it.

**Comment by theripper93** [comment]
With recent changes to levels, the levels compatibility code present in token lean (https://github.com/WesBelmont/token-lean/blob/master/compatability/levels.mjs) breaks levels. The good news is, with these recent changes Token Lean no longer needs special code for Levels.

simply not doing anything specific for levels will make both module work together again, if anyone wants to test this, simply deleting the contents of the `levels.mjs` file should fix all issues.

**Comment by WesBelmont** [comment]
Removed unnecessary compatability. Thanks @theripper93
