### ISSUE TITLE
Compatibility in v11?

### ISSUE THREAD

**Issue by Fridan99** [WesBelmont/token-lean#23]
Are there any plans to migrate to v11? Personally I have not tested if it works well in v11....

**Comment by pedrogrullada** [comment]
I have tested it and the module does not seem to be working in V11. I get this error when trying to hold Q to lean

```
script.mjs:180 Uncaught TypeError: Cannot read properties of undefined (reading 'getLocalPosition')
    at leanTowardsMouse (script.mjs:180:73)
    at enableLean (script.mjs:160:9)
    at Object.onDown (script.mjs:96:17)
    at KeyboardManager._executeKeybind (foundry.js:2500:66)
    at KeyboardManager._processKeyboardContext (foundry.js:2541:33)
    at KeyboardManager._handleKeyboardEvent (foundry.js:2599:10)
    at foundry.js:2225:54```

Foundry Build 302, Pathfinder 2e 5.0.1

**Comment by Fridan99** [comment]
I close the thread as the author has upgraded to 2.0.0
