### ISSUE TITLE
Any plans to upgrade to v12?

### ISSUE THREAD

**Issue by Fridan99** [WesBelmont/token-lean#28]
Hi!, I'm just passing by to ask if there is any plan to adapt the module to v12.... thank you :)

**Comment by Fridan99** [comment]
Foundry v12.324
Dnd5e 3.2.0

Other modues active? NO
Token Lean 2.1.0

Error type

It seems that the module does not work as expected. When press q and try to move the cursor to extend the vision range, it does not work. Nothing happens....

Console error

Uncaught TypeError: Cannot read properties of undefined (reading 'data')
    at updateVisionPosition (script.mjs:223:37)
    at enableLean (script.mjs:164:9)
    at Object.onUp (script.mjs:100:13)
    at KeyboardManager._executeKeybind (foundry.js:2438:58)
    at KeyboardManager._processKeyboardContext (foundry.js:2480:33)
    at KeyboardManager._handleKeyboardEvent (foundry.js:2538:10)
    at foundry.js:2153:52

**Comment by mclemente** [comment]
I have a working fork, you can install it with the manifest URL here https://github.com/mclemente/token-lean/releases

**Comment by Fridan99** [comment]
> I have a working fork, you can install it with the manifest URL here https://github.com/mclemente/token-lean/releases

Did you test it in 12.327? 

![Bug](https://github.com/WesBelmont/token-lean/assets/86131373/729117c3-2921-4ef4-94ef-2424fb97d4a6)

i have this bug, and only fork token lean active, no other modules :S

**Comment by mclemente** [comment]
Ah, I've tested with tokens having their own light source, that's what is causing these errors 🤦
It should be fixed with the latest release.

**Comment by Fridan99** [comment]
> Ah, I've tested with tokens having their own light source, that's what is causing these errors 🤦 It should be fixed with the latest release.

Now works like a charm with the latest update 2.2.1   (You are a genious) :P  mclemente
